/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "ISR_PWM_TC.h"
#include "Pin_TC_aliases.h"
#include "Pin_TC.h"
#include "PWM_C_L_aliases.h"
#include "PWM_C_L.h"
#include "PWM_C_U_aliases.h"
#include "PWM_C_U.h"
#include "PWM_C.h"
#include "Control_Reg_PWM_Reset.h"
#include "PWM_B_L_aliases.h"
#include "PWM_B_L.h"
#include "PWM_B_U_aliases.h"
#include "PWM_B_U.h"
#include "PWM_B.h"
#include "PWM_A_L_aliases.h"
#include "PWM_A_L.h"
#include "PWM_A_U_aliases.h"
#include "PWM_A_U.h"
#include "PWM_A.h"
#include "Pin_Hall_2_aliases.h"
#include "Pin_Hall_2.h"
#include "Pin_Hall_1_aliases.h"
#include "Pin_Hall_1.h"
#include "Pin_Hall_0_aliases.h"
#include "Pin_Hall_0.h"
#include "Status_Reg_Hall.h"
#include "Counter_Hall.h"
#include "ISR_Hall.h"
#include "Counter_16.h"
#include "ADC_DelSig_1.h"
#include "Pin_VBAT_aliases.h"
#include "Pin_VBAT.h"
#include "Pin_SW_aliases.h"
#include "Pin_SW.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "ISR_ADC_DelSig.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_Bypass_P03_aliases.h"
#include "ADC_DelSig_1_Bypass_P03.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "CydwClock_1.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

